export {
  DESKTOP_EVENT_SCHEMA,
  DESKTOP_PROTOCOL_VERSION,
  DESKTOP_REQUEST_SCHEMA,
  DESKTOP_RESPONSE_SCHEMA,
  type DesktopError,
  type DesktopErrorFields,
  type DesktopEvent,
  type DesktopEventFields,
  type DesktopFailureResponse,
  type DesktopFailureResponseFields,
  DesktopMessageValidationError,
  type DesktopProjectContext,
  type DesktopProjectContextFields,
  type DesktopRequest,
  type DesktopRequestFields,
  type DesktopResponse,
  type DesktopSuccessResponse,
  type DesktopSuccessResponseFields,
  parseDesktopEvent,
  parseDesktopRequest,
  parseDesktopResponse,
} from './desktop.js';

export {
  type AppHealthResult,
  type AppHealthResultFields,
  type CanceledDirectorySelection,
  type CanceledDirectorySelectionFields,
  type CreateProjectPayload,
  type CreateProjectPayloadFields,
  DESKTOP_METHOD_NAMES,
  DESKTOP_METHOD_PAYLOAD_SCHEMA,
  DESKTOP_METHOD_RESULT_SCHEMA,
  type DesktopMethodName,
  type DesktopMethodPayload,
  type DesktopMethodPayloadMap,
  type DesktopMethodResult,
  type DesktopMethodResultMap,
  DesktopMethodValidationError,
  type DesktopMethodValidationErrorCode,
  type DirectorySelectionPurpose,
  type EmptyDesktopMethodPayload,
  isDesktopMethodName,
  type OpenProjectPayload,
  type OpenProjectPayloadFields,
  parseDesktopMethodPayload,
  parseDesktopMethodResult,
  type ProjectSummaryDto,
  type ProjectSummaryDtoFields,
  type RecentProjectAvailability,
  type RecentProjectDto,
  type RecentProjectDtoFields,
  type RecentProjectListResult,
  type RecentProjectListResultFields,
  type RemoveRecentProjectPayload,
  type RemoveRecentProjectPayloadFields,
  type RemoveRecentProjectResult,
  type RemoveRecentProjectResultFields,
  type SelectDirectoryPayload,
  type SelectDirectoryPayloadFields,
  type SelectDirectoryResult,
  type SelectedDirectory,
  type SelectedDirectoryFields,
} from './desktopMethods.js';

export {
  BLOCK_ALIGNMENT_POLICY_VERSION,
  type ChapterCandidateV1,
  type ChapterIndexEntryV1,
  type ChapterIndexV1,
  type ChapterIndexV1Fields,
  type CoverageClassificationV1,
  type CoverageReportV1,
  type CoverageSegmentV1,
  type DocumentBlockKindV1,
  type DocumentBlockV1,
  getTxtExactLocatorKeyV1,
  type ImportedNovelV1,
  type ImportedNovelV1Fields,
  type ImportedNovelValidationContextV1,
  type ImportIssueSeverityV1,
  type ImportIssueV1,
  type ImportIssueV1Fields,
  NOVEL_IMPORT_ERROR_CODES,
  NOVEL_IMPORT_SCHEMA,
  NOVEL_IMPORT_SCHEMA_VERSION,
  NOVEL_SOURCE_FORMATS,
  type NovelImportDocumentV1,
  type NovelImportErrorCode,
  NovelImportValidationError,
  type NovelMetadataV1,
  type NovelMetadataV1Fields,
  type NovelSourceFormat,
  parseChapterCandidateV1,
  parseChapterIndexV1,
  parseImportedNovelV1,
  parseNovelImportDocumentV1,
  parseTxtSourceLocatorV1,
  type SourceByteRangeV1,
  type SourceLineRangeV1,
  type StructuralHintV1,
  TXT_SOURCE_ENCODINGS,
  type TxtEncodingDecisionMethodV1,
  type TxtEncodingDecisionV1,
  type TxtSourceEncoding,
  type TxtSourceLocatorV1,
  type TxtSourceLocatorValidationContextV1,
  type UserSelectedTxtSourceEncoding,
} from './novelImport.js';

export {
  parseProjectManifest,
  PROJECT_LAYOUT_VERSION,
  PROJECT_MANIFEST_SCHEMA,
  PROJECT_MANIFEST_SCHEMA_VERSION,
  PROJECT_MIN_LAYOUT_VERSION,
  type ProjectAccessMode,
  type ProjectContext,
  type ProjectManifest,
  type ProjectManifestFields,
  ProjectManifestValidationError,
} from './project.js';

export {
  parseProjectWriteLock,
  PROJECT_WRITE_LOCK_SCHEMA,
  PROJECT_WRITE_LOCK_SCHEMA_VERSION,
  type ProjectWriteLock,
  type ProjectWriteLockFields,
  ProjectWriteLockValidationError,
} from './projectWriteLock.js';

export {
  mapTextRangeToSingleV1,
  mapTextRangeV1,
  parseTextRangeMapRequestV1,
  parseTextRangeMapResultV1,
  parseTextRangeMapV1,
  parseTextRangeV1,
  parseTextRevisionRefV1,
  TEXT_RANGE_MAP_SCHEMA_VERSION,
  TEXT_RANGE_MAP_VERSION,
  TEXT_RANGE_MAPPING_SCHEMA_VERSION,
  TEXT_REFERENCE_SCHEMA,
  type TextLayerV1,
  type TextRangeCursorBiasV1,
  type TextRangeMapDirectionV1,
  type TextRangeMapOperationV1,
  type TextRangeMappedFragmentV1,
  TextRangeMappingReviewRequiredError,
  type TextRangeMapRequestV1,
  type TextRangeMapResultV1,
  type TextRangeMapSegmentV1,
  type TextRangeMapV1,
  type TextRangeMapV1Fields,
  type TextRangeUnmappableFragmentV1,
  type TextRangeV1,
  type TextRangeValidationContextV1,
  TextReferenceValidationError,
  type TextRevisionRefV1,
} from './text.js';

export {
  ARTIFACT_DEPENDENCY_SCHEMA,
  ARTIFACT_RECORD_SCHEMA,
  ARTIFACT_REVISION_DOCUMENT_SCHEMA,
  ARTIFACT_REVISION_DOCUMENT_SCHEMA_VERSION,
  type ArtifactDependency,
  type ArtifactDependencyFields,
  type ArtifactDependencyType,
  type ArtifactRecord,
  type ArtifactRecordFields,
  type ArtifactRevisionDependency,
  type ArtifactRevisionDependencyFields,
  type ArtifactRevisionDocument,
  type ArtifactRevisionDocumentFields,
  type ArtifactScope,
  type ArtifactSelector,
  type ArtifactStorageKind,
  type ExecutionStatus,
  EXPORT_SNAPSHOT_RECORD_SCHEMA,
  type ExportSnapshotRecord,
  type JsonArray,
  type JsonObject,
  type JsonPrimitive,
  type JsonValue,
  parseArtifactDependency,
  parseArtifactRecord,
  parseArtifactRevisionDocument,
  parseExportSnapshotRecord,
  parseProjectRecord,
  parseReviewDecisionRecord,
  parseSourceAssetRecord,
  parseStageRunRecord,
  parseStaleCause,
  parseTaskRecord,
  PROJECT_RECORD_SCHEMA,
  type ProjectRecord,
  REVIEW_DECISION_RECORD_SCHEMA,
  type ReviewDecisionRecord,
  type ReviewStatus,
  SOURCE_ASSET_RECORD_SCHEMA,
  type SourceAssetRecord,
  STAGE_RUN_RECORD_SCHEMA,
  type StageRunRecord,
  STALE_CAUSE_SCHEMA,
  type StaleCause,
  type StaleCauseFields,
  TASK_RECORD_SCHEMA,
  type TaskRecord,
  type TaskRecordFields,
  type TaskRecoveryStatus,
  type ValidityStatus,
  WorkflowRecordValidationError,
} from './workflow.js';
